---
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "rewriter.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
      {{- include "rewriter.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}

  ports:
    - name: milter
      protocol: TCP
      port: {{ .Values.rewriter.listeningPort }}
      targetPort: 8800
